app:
  jwtSecret: ${JWT_SECRET_KEY}
  jwtExpirationMs: 600000
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
springdoc:
  packagesToScan: yummydelivery.server.api
  pathsToMatch: /api/v1/**
  swagger-ui:
    operationsSorter: method
    disable-swagger-default-url: true
    url: /v3/api-docs
    tags-sorter: alpha
  show-actuator: true
  api-docs:
    version: openapi_3_0
